name: managertime
description: "A new Flutter project."

publish_to: 'none' # Optional, for private packages

version: 1.0.0+1

environment:
  sdk: "^3.6.0-334.3.beta"  # Specific Flutter SDK version (beta)

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  path_provider: ^2.1.5
  mobile_scanner: ^6.0.2
  permission_handler: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Specify assets correctly
  assets:
    - assets/images/logo.jpg  # Correct path to the image file
